## 資料[iris.csv](../../dataset/iris.csv)的前3行
```
150,4,setosa,versicolor,virginica
5.1,3.5,1.4,0.2,0
4.9,3.0,1.4,0.2,0
```
## 一般讀取CSV方法

In [2]:
import csv

In [3]:
handle=open('../dataset/iris.csv')
rst=csv.reader(handle)

In [5]:
x=next(rst) #讀取下一行
x
handle.close()

['5.1', '3.5', '1.4', '0.2', '0']

### 讀成dict: 函數DictReader()

In [16]:
"""
檔案abc.csv 內容
a,b,c
1,2,3
4,5,6
"""
handle=open('abc.csv')
reader1 = csv.DictReader(handle) #把每一行讀成dict

print(reader1.fieldnames) # ['a', 'b', 'c']

for row in reader1:
    print(row['a'], row['b'])
handle.close()

['a', 'b', 'c']
1 2
4 5


但是有些CSV資料,並不是像上面的例子那樣安排,例如本文提及的[iris.csv](../../dataset/iris.csv)(參考開頭的部分) 

In [17]:

handle=open('../../dataset/iris.csv')

reader1 = csv.DictReader(handle)
print(reader1)
print(reader1.fieldnames) # 雖然沒有錯誤,但是讀到的是 ['150', '4', 'setosa', 'versicolor', 'virginica']
handle.close()

['150', '4', 'setosa', 'versicolor', 'virginica']


## 利用numpy

In [10]:
import csv
import numpy as np
handle=open('../../dataset/iris.csv')        
data_file = csv.reader(handle)
temp = next(data_file) # 讀入第一行
n_samples = int(temp[0]) # 第一行,第1個元素是,總樣本數
n_features = int(temp[1]) # 第一行,第2個元素是,欄位個數
xx=temp[2:]
target_names = np.array(temp[2:]) # 第一行,其他欄位是輸出y號碼代表的類別
print(target_names)
data = np.empty((n_samples, n_features))
target = np.empty((n_samples,), dtype=int)

for i, ir in enumerate(data_file):
    data[i] = np.asarray(ir[:-1], dtype=np.float64)
    target[i] = np.asarray(ir[-1], dtype=int)

handle.close()
print("X資料前5")
print(data[0:5])
print("y資料前5")
print(target_names[target[0:5]])


['setosa' 'versicolor' 'virginica']
X資料前5
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y資料前5
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']
