In [4]:
#import matplotlib.pyplot as plt
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[11,12],[13,14]])
print(b)
print(np.dot(a,b))
#[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
print(np.matmul(a,b))
print(a@b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[37 40]
 [85 92]]
[[37 40]
 [85 92]]
[[37 40]
 [85 92]]
